"use client";
import Footer from "./components/Footer/footer";
import "./globals.css";
import type { Metadata } from "next";
import { Provider } from "react-redux";
import { store } from "./redux/store";

export const metadata: Metadata = {
    title: "rustservers.io",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className="bg-neutral-900">
                <Provider store={store}>
                    {children}
                    <Footer />
                </Provider>
            </body>
        </html>
    );
}
